name: Build Helioviewer Containers
description: Builds all Helioviewer container images

inputs:
  push:
    description: Whether to push images to registry (requires write permissions)
    required: false
    default: 'false'
  load:
    description: Whether to load images into Docker (cannot be used with push or multi-platform builds)
    required: false
    default: 'false'
  arch:
    description: Target architecture when loading (e.g., linux/amd64, linux/arm64)
    required: false
    default: 'linux/amd64'

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Buildx (local driver for dependent images)
      uses: docker/setup-buildx-action@v3
      id: buildx-local
      with:
        driver: docker

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push node image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/node.Dockerfile
        platforms: ${{ inputs.load == 'true' && inputs.arch || 'linux/amd64,linux/arm64' }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: |
          ghcr.io/helioviewer-project/node:latest
          ghcr.io/helioviewer-project/node:${{ github.sha }}

    - name: Build and push python image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/python.Dockerfile
        platforms: linux/amd64
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: |
          ghcr.io/helioviewer-project/python:latest
          ghcr.io/helioviewer-project/python:${{ github.sha }}

    - name: Build and push php image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/php.Dockerfile
        platforms: linux/amd64
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: |
          ghcr.io/helioviewer-project/php:latest
          ghcr.io/helioviewer-project/php:${{ github.sha }}
        builder: ${{ steps.buildx-local.outputs.name }}

    - name: Build and push movie-worker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/movies.Dockerfile
        platforms: linux/amd64
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: |
          ghcr.io/helioviewer-project/movie-worker:latest
          ghcr.io/helioviewer-project/movie-worker:${{ github.sha }}
        builder: ${{ steps.buildx-local.outputs.name }}
