name: helioviewer
services:
  # Relational database for helioviewer
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_password
    restart: always
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 5s
      timeout: 5s
      retries: 3
    secrets:
      - mariadb_password
  # In memory cache for helioviewer
  redis:
    image: redis:latest
    restart: always
  # Database initializer (creates tables + helioviewer user account)
  database_setup:
    image: dgarciabriseno/helioviewer-db-init:${TAG}
    platform: linux/amd64
    depends_on:
      database:
        condition: service_healthy
    build:
      dockerfile: ./compose.prod/dockerfiles/db_init.prod.Dockerfile
      context: .
    secrets:
      - api_settings
      - db_setup_script
    volumes:
      - jp2_volume:/tmp/jp2
  api:
    image: dgarciabriseno/helioviewer-api:${TAG}
    build:
      dockerfile: ./compose.prod/dockerfiles/api.prod.Dockerfile
      context: .
    ports:
      - 8081:80
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      database_setup:
        condition: service_completed_successfully
    restart: always
    platform: linux/amd64
    healthcheck:
      # Check every 10 seconds, wait up to 2 minutes
      test: ["CMD", "ls", "/tmp/container_ready"]
      interval: 10s
      timeout: 1s
      retries: 12
    volumes:
      - cache:/var/www/helioviewer.org/cache
      - cache:/var/www/api.helioviewer.org/docroot/cache
      - api_logs:/var/www/api.helioviewer.org/log
      - jp2_volume:/tmp/jp2
    secrets:
      - api_config
      - api_private
  web:
    image: dgarciabriseno/helioviewer-web:${TAG}
    build:
      dockerfile: ./compose.prod/dockerfiles/webserver.prod.Dockerfile
    ports:
      - 8080:80
    depends_on:
      api:
        condition: service_healthy
    restart: always
    volumes:
      - cache:/var/www/html/cache
    secrets:
      - api_config
      - api_private
      - config_js
  movies:
    image: dgarciabriseno/helioviewer-movies:${TAG}
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_healthy
    build:
      dockerfile: ./compose.prod/dockerfiles/movie_builder.Dockerfile
    platform: linux/x86_64
    volumes:
      - jp2_volume:/tmp/jp2
      - cache:/var/www/helioviewer.org/cache
      - movie_logs:/var/www/api.helioviewer.org/log
    secrets:
      - api_config
      - api_private
  soho:
    image: dgarciabriseno/helioviewer-downloader:${TAG}
    command: "-d hv_soho"
    restart: always
    platform: linux/x86_64
    build:
      dockerfile: ./compose.prod/dockerfiles/downloader.Dockerfile
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - jp2_volume:/tmp/jp2
    secrets:
      - api_settings
  sdo:
    image: dgarciabriseno/helioviewer-downloader:${TAG}
    command: "-d lmsal"
    restart: always
    platform: linux/x86_64
    build:
      dockerfile: ./compose.prod/dockerfiles/downloader.Dockerfile
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - jp2_volume:/tmp/jp2
    secrets:
      - api_settings
  stereo:
    image: dgarciabriseno/helioviewer-downloader:${TAG}
    command: "-d hv_stereo"
    restart: always
    platform: linux/x86_64
    build:
      dockerfile: ./compose.prod/dockerfiles/downloader.Dockerfile
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - jp2_volume:/tmp/jp2
    secrets:
      - api_settings

volumes:
  jp2_volume:
  cache:
  api_logs:
  movie_logs:

secrets:
  mariadb_password:
    file: secrets/mariadb_password
  api_config:
    file: secrets/Config.ini
  api_private:
    file: secrets/Private.php
  api_settings:
    file: secrets/settings.cfg
  db_setup_script:
    file: secrets/headless_setup.sh
  config_js:
    file: secrets/Config.js
